### ISSUE TITLE
To Create a GH page to deploy test reports directly using 3rd party actions

### ISSUE THREAD

**Issue by sven6002** [conda/infrastructure#646]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The Idea is to add Allure Reports and the history trend that can show the test cases relevance, validity and performance  of the test suite by using 3rd party Actions from 

- Simple elf for setting up allure reports
- PaceIris acting to deploy the generated allure report that will also contain the history of the run 
- Sibz to post the link directly as a html page so consumers could view the report of the test run
- Slack channel addition to add the report to the Slack Channel of our choosing. 

```
- name: Setup allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

- name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: <GITHUBPAGE. Token>
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

- name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
            context: 'Allure Test Report'
            state: 'success'
            sha: ${{ github.event.pull_request.head.sha }}
            target_url: sven6002.github.io/conda-build/github-allure-history/${{ github.run_number }}

- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.23.0
  with:
    # Slack channel id, channel name, or user id to post message.
    # See also: https://api.slack.com/methods/chat.postMessage#channels
    # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
    channel-id: 'CHANNEL_ID,ANOTHER_CHANNEL_ID'
    # For posting a simple plain text message
    slack-message: "result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
  env: SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

```

### Why is this needed?

This will provide a wholistic representation of the test suite run on GH CI on regular cadence. This allows the user to prepare more proficient and relevant test cases with visually seen workflows.. 

### What should happen?

We will need to be able to create 

- GH page with deploy tags to allow the reports to be added for the run 
- The slack channel for posting the generated result with the `allure-report.html`
